# Generated by Django 5.0.1 on 2024-05-02 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('is_valid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserBasicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('user_metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_devfolio.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserPhotoProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.CharField(max_length=256)),
                ('timestamp', models.DateTimeField()),
                ('user_metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_devfolio.user')),
            ],
        ),
    ]
