# Generated by Django 5.0.1 on 2024-06-05 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_devfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eduworkproject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.TextField()),
                ('work_experience', models.TextField()),
                ('project', models.TextField()),
                ('user_metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_devfolio.user')),
            ],
        ),
    ]
