from django.db import models

# Create your models here.


class User(models.Model):
    """
    This class represents a table in sql where following columns are present:
    1. id (primary key): row number generated by django automatically.
    2. user_email: user's email
    3. is_valid: if user has validated the email
    """
    user_email = models.EmailField(null=False)
    is_valid = models.BooleanField(null=False, default=False)


class UserBasicProfile(models.Model):
    """
    This class represents a table in sql where following columns are present:
    1. id (primary key): row number generated by django automatically.
    2. first_name: user's first name
    3. last_name: user's last name
    4. user_metadata (foreign key): this column contains user data such as email and user_id.
    """
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    user_metadata = models.ForeignKey(User, on_delete=models.CASCADE)


class UserPhotoProfile(models.Model):
    """
    This class represents a table in sql where following columns are present:
    1. id (primary key): row number generated by django automatically.
    2. photo_url: s3 path of local file path of user's profile photo
    3. user_metadata (foreign key): this column contains user data such as email and user_id.
    This column can be used to join tables in sql
    4. timestamp: timestamp to indicate when the profile photo was uploaded
    """
    photo_url = models.CharField(null=False, max_length=256)
    user_metadata = models.ForeignKey(User, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(null=False, blank=False)
